# processes and tries to compile latex. 
# issue is that latex is not great, 
# and i need a new way to generate that latex. 
import os
import shutil
import subprocess
import logging
import re
from multiprocessing import Pool
from pdf2image import convert_from_path
from google import genai
from tenacity import retry, stop_after_attempt, wait_exponential

# ==========================================
# 1. Logging Setup
# ==========================================
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s [%(levelname)s] %(message)s',
    handlers=[logging.FileHandler("processing_trace.log"), logging.StreamHandler()]
)

def log(msg, filename):
    logging.info(f"[{filename}] {msg}")

# ==========================================
# 2. Configuration
# ==========================================
API_KEY = "AIzaSyACloyikx6S1JqZfk3daRG9XTGwTMSWn7E"
MODEL_NAME = 'gemini-2.5-flash-lite'
MAX_CONCURRENT_FILES = 6
INPUT_DIR = "." 
OUTPUT_DIR = "./processed_pdfs"
WORK_DIR = "./workspace"

LATEX_TEMPLATE = r"""\documentclass[11pt,a4paper]{{article}}
\usepackage[utf8]{{inputenc}}
\usepackage{{amsmath, amssymb, amsfonts}}
\usepackage{{graphicx}}
\usepackage{{xcolor}}
\usepackage[normalem]{{ulem}} 
\usepackage{{cancel}}        
\usepackage{{enumitem}}      
\usepackage{{geometry}}      
\geometry{{margin=1in}}
\begin{{document}}
{}
\end{{document}}
"""

def clean_output(text):
    # 1. Remove markdown code blocks
    text = re.sub(r"```latex", "", text, flags=re.IGNORECASE)
    text = re.sub(r"```", "", text, flags=re.IGNORECASE)
    
    # 2. Aggressively strip preamble commands
    text = re.sub(r"\\documentclass.*", "", text)
    text = re.sub(r"\\usepackage\{.*?\}", "", text)
    text = re.sub(r"\\begin\{document\}", "", text)
    text = re.sub(r"\\end\{document\}", "", text)
    
    # 3. Strip structural quote commands if they cause nesting issues
    text = text.replace(r"\begin{quote}", "").replace(r"\end{quote}", "")
    
    # 4. Fix common broken LaTeX syntax generated by LLMs
    text = text.replace(r"&", r"\&") # Escape alignment tabs
    text = re.sub(r"\\left(?![^{])", "", text) # Remove dangling left
    text = re.sub(r"\\right(?![^{])", "", text) # Remove dangling right
    
    return text.strip()

def init_worker(api_key):
    global client
    client = genai.Client(api_key=api_key)

@retry(stop=stop_after_attempt(3), wait=wait_exponential(multiplier=1, min=2, max=10))
def call_gemini_with_retry(img, prompt):
    return client.models.generate_content(
        model=MODEL_NAME,
        contents=[img, prompt]
    )

def process_single_pdf(pdf_filename):
    if pdf_filename.startswith("processed_"):
        return

    pdf_base = os.path.splitext(pdf_filename)[0]
    workspace = os.path.join(WORK_DIR, pdf_base)
    figures_dir = os.path.join(workspace, "figures")
    os.makedirs(figures_dir, exist_ok=True)

    log("Initializing workspace.", pdf_filename)
    
    try:
        pages = convert_from_path(pdf_filename, dpi=200)
    except Exception as e:
        log(f"FAILED during extraction: {e}", pdf_filename)
        return

    latex_content = ""
    
    for i, page_img in enumerate(pages):
        img_name = f"page_{i+1}.png"
        img_path = os.path.join(figures_dir, img_name)
        page_img.save(img_path, "PNG")
        
        log(f"Transcribing page {i+1}/{len(pages)}.", pdf_filename)
        
        # Strict prompt to prevent boilerplate hallucination
        prompt = (
            "Transcribe this handwritten math page into LaTeX. "
            "Output ONLY the LaTeX body content. "
            "DO NOT include: \\usepackage, \\documentclass, \\begin{document}, \\end{document}. "
            "Ensure all math is properly closed with '$' or environment tags. "
        )
        
        try:
            response = call_gemini_with_retry(page_img, prompt)
            # Use \par instead of quote to avoid nested environment errors
            latex_content += f"""\\subsection*{{Page {i+1}}}
\\includegraphics[width=0.6\\textwidth]{{figures/{img_name}}}
\\par {clean_output(response.text)} \\newpage\n"""
        except Exception as e:
            log(f"FAILED page {i+1} after retries: {e}", pdf_filename)
            latex_content += f"\\subsection*{{Page {i+1}}} \\par \\textit{{Transcription failed.}} \\newpage\n"

    tex_path = os.path.join(workspace, "manuscript.tex")
    with open(tex_path, "w", encoding="utf-8") as f:
        f.write(LATEX_TEMPLATE.format(latex_content))

    log("Compiling with XeLaTeX.", pdf_filename)
    try:
        # Run twice to resolve references
        for _ in range(2):
            subprocess.run(["xelatex", "-interaction=nonstopmode", "manuscript.tex"], 
                           cwd=workspace, stdout=subprocess.DEVNULL)
        
        if os.path.exists(os.path.join(workspace, "manuscript.pdf")):
            shutil.move(os.path.join(workspace, "manuscript.pdf"), 
                        os.path.join(OUTPUT_DIR, f"processed_{pdf_filename}"))
            log("SUCCESS.", pdf_filename)
        else:
            log("COMPILATION FAILED: No PDF produced.", pdf_filename)
    except Exception as e:
        log(f"SYSTEM ERROR: {e}", pdf_filename)

def main():
    os.makedirs(OUTPUT_DIR, exist_ok=True)
    os.makedirs(WORK_DIR, exist_ok=True)
    
    files = ['amt-c-11-to20-5.pdf']
    print(f"Processing {len(files)} files...")
    with Pool(processes=MAX_CONCURRENT_FILES, initializer=init_worker, initargs=(API_KEY,)) as pool:
        pool.map(process_single_pdf, files)

if __name__ == "__main__":
    main()